### ISSUE TITLE
Method ask raising [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")

### ISSUE THREAD

**Issue by bagi3mk** [usernein/pyromod#20]
i got this error
`pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")`

when i use this code :
```python
Phone_Number = await client.ask(chat,f"- قم بأرسال رقم الهاتف .")
```

why???

full error:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.9/dist-packages/pyromod/listen/listen.py", line 293, in resolve_future
    await self.registered_handler(client, query, *args)
  File "/root/Tmoel/plugins/Main.py", line 554, in Call_Start
    Phone_Number = await client.ask(int(chat),f"- قم بأرسال رقم الهاتف .")
  File "/usr/local/lib/python3.9/dist-packages/pyromod/listen/listen.py", line 99, in ask
    request = await self.send_message(identifier[0], text, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
    peer=await self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 76, in resolve_peer
    await self.invoke(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")
```

**Comment by usernein** [comment]
@bagi3mk What is in the variable chat?

**Comment by bagi3mk** [comment]
@usernein it's like any chat id : 683470553

**Comment by bagi3mk** [comment]
> @bagi3mk What is in the variable chat?

 it's like any chat id : 683470553

**Comment by CallMyNameStar** [comment]
anyone found a way?
