### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by MahdeenSky** [usernein/pyromod#7]
Everything seems to work fine but there is this peculiar error message that seems impossible to debug because its a fault within the module itself.
```
2022-07-28 10:08:31,968 - pyrogram.connection.connection - INFO - Connecting...
2022-07-28 10:08:32,059 - pyrogram.connection.connection - INFO - Connected! Production DC4 - IPv4 - TCPAbridgedO
2022-07-28 10:08:32,060 - pyrogram.session.session - INFO - NetworkTask started
2022-07-28 10:08:32,293 - pyrogram.session.internals.msg_id - INFO - Time synced: 2022-07-28 07:08:32.354201 UTC
2022-07-28 10:08:32,500 - pyrogram.session.session - INFO - Session initialized: Layer 142
2022-07-28 10:08:32,500 - pyrogram.session.session - INFO - Device: CPython 3.8.9 - Pyrogram 2.0.26
2022-07-28 10:08:32,500 - pyrogram.session.session - INFO - System: Darwin 20.6.0 (EN)
2022-07-28 10:08:32,500 - pyrogram.session.session - INFO - Session started
2022-07-28 10:08:32,504 - pyrogram.session.session - INFO - PingTask started
2022-07-28 10:08:32,607 - pyrogram.dispatcher - INFO - Started 12 HandlerTasks
2022-07-28 10:08:41,467 - pyrogram.dispatcher - ERROR - object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/Users/smi/Library/Python/3.8/lib/python/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/Users/smi/Library/Python/3.8/lib/python/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
TypeError: object NoneType can't be used in 'await' expression
[request] Processing Link 'https://www.youtube.com/watch?v=tPEE9ZwTmy0&ab_channel=MylotheCat' from 'MahdeenSky'
[request] Downloaded Video at 'https://www.youtube.com/watch?v=tPEE9ZwTmy0&ab_channel=MylotheCat' with filesize: 0.069438
2022-07-28 10:08:43,835 - pyrogram.connection.connection - INFO - Connecting...
2022-07-28 10:08:43,931 - pyrogram.connection.connection - INFO - Connected! Production DC4 (media) - IPv4 - TCPAbridgedO
2022-07-28 10:08:43,932 - pyrogram.session.session - INFO - NetworkTask started
2022-07-28 10:08:44,391 - pyrogram.session.session - INFO - Session initialized: Layer 142
2022-07-28 10:08:44,392 - pyrogram.session.session - INFO - Device: CPython 3.8.9 - Pyrogram 2.0.26
2022-07-28 10:08:44,392 - pyrogram.session.session - INFO - System: Darwin 20.6.0 (EN)
2022-07-28 10:08:44,392 - pyrogram.session.session - INFO - Session started
2022-07-28 10:08:44,393 - pyrogram.session.session - INFO - PingTask started
2022-07-28 10:08:44,702 - pyrogram.session.session - INFO - PingTask stopped
2022-07-28 10:08:44,702 - pyrogram.connection.connection - INFO - Disconnected
2022-07-28 10:08:44,703 - pyrogram.session.session - INFO - NetworkTask stopped
2022-07-28 10:08:44,703 - pyrogram.session.session - INFO - Session stopped
```

**Comment by usernein** [comment]
Thanks for reporting!
Fixed in [pyromod v3](https://github.com/usernein/pyromod/releases/tag/v3.0.0)!
